import {
  LayoutGrid,
  List,
  Activity,
  Search,
  Plus,
  Sparkles,
  Send,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  Settings,
  Sun,
  Moon,
  Check,
  CheckCheck,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  MoreHorizontal,
  Mail,
  Phone,
  Calendar,
  MessageCircle,
  MessageSquare,
  Megaphone,
  FileText,
  File,
  Paperclip,
  Building2,
  Users,
  Box,
  Target,
  LifeBuoy,
  Receipt,
  Layers,
  Filter,
  Download,
  Trash2,
  Pencil,
  Star,
  Flag,
  Clock,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  Zap,
  Command,
  Eye,
  CircleDollarSign,
  Briefcase,
  PanelLeft,
  GripVertical,
  Undo2,
  Redo2,
  ListChecks,
  SlidersHorizontal,
  RotateCcw,
  Sparkle,
  Minus,
  Maximize2,
  Upload,
  Table2,
  Database,
  Clipboard,
  RefreshCw,
  Wand2,
  type LucideIcon,
} from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
  grid: LayoutGrid,
  list: List,
  activity: Activity,
  search: Search,
  plus: Plus,
  sparkles: Sparkles,
  send: Send,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  bell: Bell,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  check: Check,
  checkCheck: CheckCheck,
  x: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  more: MoreHorizontal,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  whatsapp: MessageCircle,
  chat: MessageCircle,
  sms: MessageSquare,
  megaphone: Megaphone,
  marketing: Megaphone,
  file: File,
  fileText: FileText,
  note: FileText,
  paperclip: Paperclip,
  building: Building2,
  users: Users,
  box: Box,
  target: Target,
  'life-buoy': LifeBuoy,
  receipt: Receipt,
  layers: Layers,
  filter: Filter,
  download: Download,
  trash: Trash2,
  pencil: Pencil,
  star: Star,
  flag: Flag,
  clock: Clock,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  alert: AlertTriangle,
  zap: Zap,
  command: Command,
  eye: Eye,
  dollar: CircleDollarSign,
  briefcase: Briefcase,
  panelLeft: PanelLeft,
  grip: GripVertical,
  undo: Undo2,
  redo: Redo2,
  tasks: ListChecks,
  sliders: SlidersHorizontal,
  reset: RotateCcw,
  sparkle: Sparkle,
  minus: Minus,
  expand: Maximize2,
  upload: Upload,
  sheet: Table2,
  database: Database,
  clipboard: Clipboard,
  refresh: RefreshCw,
  wand: Wand2,
};

// Map activity types to icons
export const ACTIVITY_ICONS: Record<string, string> = {
  note: 'note',
  email: 'mail',
  call: 'phone',
  meeting: 'calendar',
  whatsapp: 'whatsapp',
  sms: 'sms',
  marketing: 'marketing',
  task: 'check',
  file: 'file',
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
  color?: string;
}

export function Icon({ name, size = 16, className, strokeWidth = 1.9, color }: IconProps) {
  const Cmp = MAP[name] ?? Box;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} color={color} aria-hidden />;
}
